# Generated by Django 6.0.5 on 2026-05-28 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('clasificacion_imc', models.CharField(blank=True, choices=[('bajo_peso', 'Bajo Peso'), ('normal', 'Normal'), ('sobrepeso', 'Sobrepeso'), ('obesidad', 'Obesidad')], max_length=20, null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('glucosa', models.FloatField(blank=True, null=True)),
                ('colesterol', models.FloatField(blank=True, null=True)),
                ('saturacion_oxigeno', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('fumador', models.BooleanField(default=False)),
                ('consumo_alcohol', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(blank=True, choices=[('sedentario', 'Sedentario'), ('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=20, null=True)),
                ('diagnostico_preliminar', models.CharField(blank=True, max_length=200, null=True)),
                ('riesgo_enfermedad', models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=10, null=True)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('es_critico', models.BooleanField(default=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['id_paciente'],
            },
        ),
        migrations.CreateModel(
            name='HistorialETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=255)),
                ('registros_entrada', models.IntegerField(default=0)),
                ('registros_limpios', models.IntegerField(default=0)),
                ('duplicados_eliminados', models.IntegerField(default=0)),
                ('nulos_tratados', models.IntegerField(default=0)),
                ('tiempo_ejecucion_seg', models.FloatField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('log_detalle', models.TextField(blank=True)),
                ('errores', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial ETL',
                'verbose_name_plural': 'Historial ETL',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
