# Generated by Django 4.2.16 on 2026-06-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='clasificacion_presion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
