# Generated by Django 4.2.16 on 2026-06-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_paciente_clasificacion_presion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='historialetl',
            index=models.Index(fields=['estado'], name='etl_histori_estado_0474f2_idx'),
        ),
        migrations.AddIndex(
            model_name='historialetl',
            index=models.Index(fields=['fecha_ejecucion'], name='etl_histori_fecha_e_6e0133_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['riesgo_enfermedad'], name='etl_pacient_riesgo__70a934_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['es_critico'], name='etl_pacient_es_crit_2aff3f_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['fecha_consulta'], name='etl_pacient_fecha_c_84f7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['id_paciente'], name='etl_pacient_id_paci_f02468_idx'),
        ),
    ]
