# Generated by Django 4.2.16 on 2026-06-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_paciente_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='frecuencia_cardiaca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='presion_diastolica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='presion_sistolica',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
