# Generated by Django 6.0.5 on 2026-05-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('total_pacientes', models.IntegerField(default=0)),
                ('pacientes_criticos', models.IntegerField(default=0)),
                ('pacientes_hipertensos', models.IntegerField(default=0)),
                ('pacientes_diabeticos', models.IntegerField(default=0)),
                ('pacientes_fumadores', models.IntegerField(default=0)),
                ('promedio_edad', models.FloatField(null=True)),
                ('promedio_imc', models.FloatField(null=True)),
                ('promedio_glucosa', models.FloatField(null=True)),
                ('promedio_colesterol', models.FloatField(null=True)),
                ('riesgo_bajo', models.IntegerField(default=0)),
                ('riesgo_medio', models.IntegerField(default=0)),
                ('riesgo_alto', models.IntegerField(default=0)),
                ('riesgo_critico', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estadística Clínica',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
