# Generated by Django 4.2.16 on 2026-06-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticaclinica',
            options={'ordering': ['-fecha_calculo'], 'verbose_name': 'Estadística Clínica', 'verbose_name_plural': 'Estadísticas Clínicas'},
        ),
        migrations.AddIndex(
            model_name='estadisticaclinica',
            index=models.Index(fields=['fecha_calculo'], name='analytics_e_fecha_c_ebc370_idx'),
        ),
    ]
