# Generated by Django 6.0.5 on 2026-05-28 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('algoritmo', models.CharField(choices=[('logistic_regression', 'Regresión Logística'), ('decision_tree', 'Árbol de Decisión'), ('random_forest', 'Random Forest')], max_length=30)),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(null=True)),
                ('precision', models.FloatField(null=True)),
                ('recall', models.FloatField(null=True)),
                ('f1_score', models.FloatField(null=True)),
                ('matriz_confusion', models.JSONField(null=True)),
                ('variables_predictoras', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo ML',
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad_riesgo', models.FloatField()),
                ('riesgo_predicho', models.CharField(max_length=10)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml.modeloml')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='etl.paciente')),
            ],
            options={
                'verbose_name': 'Predicción',
                'ordering': ['-fecha_prediccion'],
            },
        ),
    ]
