# Generated by Django 4.2.16 on 2026-06-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloml',
            options={'ordering': ['-fecha_entrenamiento'], 'verbose_name': 'Modelo ML', 'verbose_name_plural': 'Modelos ML'},
        ),
        migrations.AlterModelOptions(
            name='prediccionpaciente',
            options={'ordering': ['-fecha_prediccion'], 'verbose_name': 'Predicción', 'verbose_name_plural': 'Predicciones'},
        ),
        migrations.AddIndex(
            model_name='modeloml',
            index=models.Index(fields=['algoritmo'], name='ml_modeloml_algorit_3ec94e_idx'),
        ),
        migrations.AddIndex(
            model_name='modeloml',
            index=models.Index(fields=['activo'], name='ml_modeloml_activo_450c08_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccionpaciente',
            index=models.Index(fields=['riesgo_predicho'], name='ml_predicci_riesgo__ca8f96_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccionpaciente',
            index=models.Index(fields=['fecha_prediccion'], name='ml_predicci_fecha_p_e1f1be_idx'),
        ),
    ]
