# Generated by Django 4.2.16 on 2026-06-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='authenticat_rol_480555_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='authenticat_email_de8a1c_idx'),
        ),
    ]
